Repository sgsellan/gpytoolbox, pull requests merged in 2024-06, with the labels that each got.

#116 adding DEC operators
  src/gpytoolbox/__init__.py
  src/gpytoolbox/cotangent_laplacian_intrinsic.py
  src/gpytoolbox/dec_d0.py
  src/gpytoolbox/dec_d1.py
  src/gpytoolbox/dec_h0.py
  src/gpytoolbox/dec_h0_intrinsic.py
  src/gpytoolbox/dec_h0inv.py
  src/gpytoolbox/dec_h0inv_intrinsic.py
  src/gpytoolbox/dec_h1.py
  src/gpytoolbox/dec_h1_intrinsic.py
  src/gpytoolbox/dec_h1inv.py
  src/gpytoolbox/dec_h1inv_intrinsic.py
  src/gpytoolbox/dec_h2.py
  src/gpytoolbox/dec_h2_intrinsic.py
  src/gpytoolbox/dec_h2inv.py
  src/gpytoolbox/dec_h2inv_intrinsic.py
  test/test_dec_d0.py
  test/test_dec_d1.py
  test/test_dec_h0.py
  test/test_dec_h0_intrinsic.py
  test/test_dec_h0inv.py
  test/test_dec_h0inv_intrinsic.py
  test/test_dec_h1.py
  test/test_dec_h1_intrinsic.py
  test/test_dec_h1inv.py
  test/test_dec_h1inv_intrinsic.py
  test/test_dec_h2.py
  test/test_dec_h2_intrinsic.py
  test/test_dec_h2inv.py
  test/test_dec_h2inv_intrinsic.py
Labels: enhancement, ready to merge

#114 Switching out parameters in torus function
  src/gpytoolbox/torus.py
Labels: ready to merge, breaking change

#117 Adding Poisson surface reconstruction bindings
  CMakeLists.txt
  LICENSE.GPL
  LICENSE.MIT
  cmake/PoissonRecon.cmake
  src/cpp/binding_point_cloud_to_mesh.cpp
  src/cpp/gpytoolbox_bindings_core.cpp
  src/cpp/point_cloud_to_mesh.cpp
  src/cpp/point_cloud_to_mesh.h
  src/gpytoolbox/__init__.py
  src/gpytoolbox/point_cloud_to_mesh.py
  src/gpytoolbox/stochastic_poisson_surface_reconstruction.py
  test/test_point_cloud_to_mesh.py
  test/test_stochastic_poisson_surface_reconstruction.py
Labels: enhancement, ready to merge, breaking change

#121 Reach for the arcs
  .github/workflows/ciwheels.yml
  CMakeLists.txt
  LICENSE.MIT
  cmake/glfw3webgpu.cmake
  cmake/nanoflann.cmake
  cmake/webgpu.cmake
  src/cpp/gpytoolbox_bindings_core.cpp
  src/cpp/reach_for_the_arcs/binding_fine_tune_point_cloud_iter.cpp
  src/cpp/reach_for_the_arcs/binding_locally_make_feasible.cpp
  src/cpp/reach_for_the_arcs/binding_outside_points_from_rasterization.cpp
  src/cpp/reach_for_the_arcs/fine_tune_point_cloud_iter.cpp
  src/cpp/reach_for_the_arcs/fine_tune_point_cloud_iter.h
  src/cpp/reach_for_the_arcs/locally_make_feasible.cpp
  src/cpp/reach_for_the_arcs/locally_make_feasible.h
  src/cpp/reach_for_the_arcs/outside_points_from_rasterization.cpp
  src/cpp/reach_for_the_arcs/outside_points_from_rasterization.h
  src/cpp/reach_for_the_arcs/resolve_collisions_on_sphere.cpp
  src/cpp/reach_for_the_arcs/resolve_collisions_on_sphere.h
  src/cpp/reach_for_the_arcs/sAABB.cpp
  src/cpp/reach_for_the_arcs/sAABB.h
  src/gpytoolbox/__init__.py
  src/gpytoolbox/reach_for_the_arcs.py
  src/gpytoolbox/reach_for_the_spheres.py
  test/test_reach_for_the_arcs.py
  test/unit_tests_data/R.npy
Labels: ready to merge

#122 Address numpy deprecation warning
  src/gpytoolbox/particle_swarm.py
  src/gpytoolbox/ray_mesh_intersect.py
  src/gpytoolbox/squared_distance.py
  test/test_particle_swarm.py
Labels: ready to merge

#124 making rfta test run faster and fixing bug in rfta
  src/gpytoolbox/reach_for_the_arcs.py
  test/test_reach_for_the_arcs.py
Labels: ready to merge

#125 New version number - Push before new release
  setup.py
  src/gpytoolbox/__init__.py
Labels: ready to merge
